/*! Javascript plotting library for jQuery, v. 0.7.
 *
 * Released under the MIT license by IOLA, December 2007.
 *
 */

// first an inline dependency, jquery.colorhelpers.js, we inline it here
// for convenience

/* Plugin for jQuery for working with colors.
 * 
 * Version 1.1.
 * 
 * Inspiration from jQuery color animation plugin by John Resig.
 *
 * Released under the MIT license by Ole Laursen, October 2009.
 *
 * Examples:
 *
 *   $.color.parse("#fff").scale('rgb', 0.25).add('a', -0.5).toString()
 *   var c = $.color.extract($("#mydiv"), 'background-color');
 *   console.log(c.r, c.g, c.b, c.a);
 *   $.color.make(100, 50, 25, 0.4).toString() // returns "rgba(100,50,25,0.4)"
 *
 * Note that .scale() and .add() return the same modified object
 * instead of making a new one.
 *
 * V. 1.1: Fix error handling so e.g. parsing an empty string does
 * produce a color rather than just crashing.
 */ 
(function(g){g.color={};g.color.make=function(w,j,t,V){var q={};q.r=w||0;q.g=j||0;q.b=t||0;q.a=V!=null?V:1;q.add=function(j,g){for(var t=0;t<j.length;++t)q[j.charAt(t)]+=g;return q.normalize()};q.scale=function(j,g){for(var t=0;t<j.length;++t)q[j.charAt(t)]*=g;return q.normalize()};q.toString=function(){return q.a>=1?"rgb("+[q.r,q.g,q.b].join(",")+")":"rgba("+[q.r,q.g,q.b,q.a].join(",")+")"};q.normalize=function(){function j(g,q,t){return q<g?g:q>t?t:q}q.r=j(0,parseInt(q.r),255);q.g=j(0,parseInt(q.g),
255);q.b=j(0,parseInt(q.b),255);q.a=j(0,q.a,1);return q};q.clone=function(){return g.color.make(q.r,q.b,q.g,q.a)};return q.normalize()};g.color.extract=function(w,j){var t;do{t=w.css(j).toLowerCase();if(t!=""&&t!="transparent")break;w=w.parent()}while(!g.nodeName(w.get(0),"body"));t=="rgba(0, 0, 0, 0)"&&(t="transparent");return g.color.parse(t)};g.color.parse=function(w){var j,t=g.color.make;if(j=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(w))return t(parseInt(j[1],10),
parseInt(j[2],10),parseInt(j[3],10));if(j=/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]+(?:\.[0-9]+)?)\s*\)/.exec(w))return t(parseInt(j[1],10),parseInt(j[2],10),parseInt(j[3],10),parseFloat(j[4]));if(j=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(w))return t(parseFloat(j[1])*2.55,parseFloat(j[2])*2.55,parseFloat(j[3])*2.55);if(j=/rgba\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\s*\)/.exec(w))return t(parseFloat(j[1])*
2.55,parseFloat(j[2])*2.55,parseFloat(j[3])*2.55,parseFloat(j[4]));if(j=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(w))return t(parseInt(j[1],16),parseInt(j[2],16),parseInt(j[3],16));if(j=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(w))return t(parseInt(j[1]+j[1],16),parseInt(j[2]+j[2],16),parseInt(j[3]+j[3],16));w=g.trim(w).toLowerCase();return w=="transparent"?t(255,255,255,0):(j=L[w]||[0,0,0],t(j[0],j[1],j[2]))};var L={aqua:[0,255,255],azure:[240,255,255],beige:[245,245,220],black:[0,
0,0],blue:[0,0,255],brown:[165,42,42],cyan:[0,255,255],darkblue:[0,0,139],darkcyan:[0,139,139],darkgrey:[169,169,169],darkgreen:[0,100,0],darkkhaki:[189,183,107],darkmagenta:[139,0,139],darkolivegreen:[85,107,47],darkorange:[255,140,0],darkorchid:[153,50,204],darkred:[139,0,0],darksalmon:[233,150,122],darkviolet:[148,0,211],fuchsia:[255,0,255],gold:[255,215,0],green:[0,128,0],indigo:[75,0,130],khaki:[240,230,140],lightblue:[173,216,230],lightcyan:[224,255,255],lightgreen:[144,238,144],lightgrey:[211,
211,211],lightpink:[255,182,193],lightyellow:[255,255,224],lime:[0,255,0],magenta:[255,0,255],maroon:[128,0,0],navy:[0,0,128],olive:[128,128,0],orange:[255,165,0],pink:[255,192,203],purple:[128,0,128],violet:[128,0,128],red:[255,0,0],silver:[192,192,192],white:[255,255,255],yellow:[255,255,0]}})(jQuery);
(function(g){function L(j,t,V,q){function H(a,d){d=[y].concat(d);for(var b=0;b<a.length;++b)a[b].apply(this,d)}function Z(a){for(var d=[],b=0;b<a.length;++b){var e=g.extend(!0,{},f.series);a[b].data!=null?(e.data=a[b].data,delete a[b].data,g.extend(!0,e,a[b]),a[b].data=e.data):e.data=a[b];d.push(e)}x=d;d=x.length;b=[];e=[];for(a=0;a<x.length;++a){var c=x[a].color;c!=null&&(--d,typeof c=="number"?e.push(c):b.push(g.color.parse(x[a].color)))}for(a=0;a<e.length;++a)d=Math.max(d,e[a]+1);b=[];for(a=e=
0;b.length<d;)c=f.colors.length==a?g.color.make(100,100,100):g.color.parse(f.colors[a]),c.scale("rgb",1+(e%2==1?-1:1)*Math.ceil(e/2)*0.2),b.push(c),++a,a>=f.colors.length&&(a=0,++e);for(a=d=0;a<x.length;++a){e=x[a];if(e.color==null)e.color=b[d].toString(),++d;else if(typeof e.color=="number")e.color=b[e.color].toString();if(e.lines.show==null){var u;c=!0;for(u in e)if(e[u]&&e[u].show){c=!1;break}if(c)e.lines.show=!0}e.xaxis=P(B,N(e,"x"));e.yaxis=P(F,N(e,"y"))}C()}function N(a,d){var b=a[d+"axis"];
if(typeof b=="object")b=b.n;typeof b!="number"&&(b=1);return b}function A(){return g.grep(B.concat(F),function(a){return a})}function T(a){var d={},b,e;for(b=0;b<B.length;++b)(e=B[b])&&e.used&&(d["x"+e.n]=e.c2p(a.left));for(b=0;b<F.length;++b)(e=F[b])&&e.used&&(d["y"+e.n]=e.c2p(a.top));if(d.x1!==void 0)d.x=d.x1;if(d.y1!==void 0)d.y=d.y1;return d}function P(a,d){a[d-1]||(a[d-1]={n:d,direction:a==B?"x":"y",options:g.extend(!0,{},a==B?f.xaxis:f.yaxis)});return a[d-1]}function C(){function a(a,c,b){if(c<
a.datamin&&c!=-e)a.datamin=c;if(b>a.datamax&&b!=e)a.datamax=b}var d=Number.POSITIVE_INFINITY,b=Number.NEGATIVE_INFINITY,e=Number.MAX_VALUE,c,u,p,o,k,l,z,f,h,j;g.each(A(),function(a,c){c.datamin=d;c.datamax=b;c.used=!1});for(c=0;c<x.length;++c)k=x[c],k.datapoints={points:[]},H(I.processRawData,[k,k.data,k.datapoints]);for(c=0;c<x.length;++c){k=x[c];var Q=k.data,s=k.datapoints.format;if(!s){s=[];s.push({x:!0,number:!0,required:!0});s.push({y:!0,number:!0,required:!0});if(k.bars.show||k.lines.show&&
k.lines.fill)if(s.push({y:!0,number:!0,required:!1,defaultValue:0}),k.bars.horizontal)delete s[s.length-1].y,s[s.length-1].x=!0;k.datapoints.format=s}if(k.datapoints.pointsize==null){k.datapoints.pointsize=s.length;z=k.datapoints.pointsize;l=k.datapoints.points;insertSteps=k.lines.show&&k.lines.steps;k.xaxis.used=k.yaxis.used=!0;for(u=p=0;u<Q.length;++u,p+=z){j=Q[u];var m=j==null;if(!m)for(o=0;o<z;++o){f=j[o];if(h=s[o])if(h.number&&f!=null&&(f=+f,isNaN(f)?f=null:f==Infinity?f=e:f==-Infinity&&(f=-e)),
f==null&&(h.required&&(m=!0),h.defaultValue!=null))f=h.defaultValue;l[p+o]=f}if(m)for(o=0;o<z;++o)f=l[p+o],f!=null&&(h=s[o],h.x&&a(k.xaxis,f,f),h.y&&a(k.yaxis,f,f)),l[p+o]=null;else if(insertSteps&&p>0&&l[p-z]!=null&&l[p-z]!=l[p]&&l[p-z+1]!=l[p+1]){for(o=0;o<z;++o)l[p+z+o]=l[p+o];l[p+1]=l[p-z+1];p+=z}}}}for(c=0;c<x.length;++c)k=x[c],H(I.processDatapoints,[k,k.datapoints]);for(c=0;c<x.length;++c){k=x[c];l=k.datapoints.points;z=k.datapoints.pointsize;j=p=d;m=Q=b;for(u=0;u<l.length;u+=z)if(l[u]!=null)for(o=
0;o<z;++o)if(f=l[u+o],(h=s[o])&&!(f==e||f==-e))h.x&&(f<p&&(p=f),f>Q&&(Q=f)),h.y&&(f<j&&(j=f),f>m&&(m=f));k.bars.show&&(u=k.bars.align=="left"?0:-k.bars.barWidth/2,k.bars.horizontal?(j+=u,m+=u+k.bars.barWidth):(p+=u,Q+=u+k.bars.barWidth));a(k.xaxis,p,Q);a(k.yaxis,j,m)}g.each(A(),function(a,c){if(c.datamin==d)c.datamin=null;if(c.datamax==b)c.datamax=null})}function $(a,d){var b=document.createElement("canvas");b.className=d;b.width=E;b.height=G;a||g(b).css({position:"absolute",left:0,top:0});g(b).appendTo(j);
b.getContext||(b=window.G_vmlCanvasManager.initElement(b));b.getContext("2d").save();return b}function L(){E=j.width();G=j.height();if(E<=0||G<=0)throw"Invalid dimensions for plot, width = "+E+", height = "+G;}function aa(a){if(a.width!=E)a.width=E;if(a.height!=G)a.height=G;a=a.getContext("2d");a.restore();a.save()}function na(a){function d(a){return a}var b,e,c=a.options.transform||d,u=a.options.inverseTransform;a.direction=="x"?(b=a.scale=O/Math.abs(c(a.max)-c(a.min)),e=Math.min(c(a.max),c(a.min))):
(b=a.scale=K/Math.abs(c(a.max)-c(a.min)),b=-b,e=Math.max(c(a.max),c(a.min)));a.p2c=c==d?function(a){return(a-e)*b}:function(a){return(c(a)-e)*b};a.c2p=u?function(a){return u(e+a/b)}:function(a){return e+a/b}}function oa(a){function d(c,b){return g('<div style="position:absolute;top:-10000px;'+b+'font-size:smaller"><div class="'+a.direction+"Axis "+a.direction+a.n+'Axis">'+c.join("")+"</div></div>").appendTo(j)}var b=a.options,e,c=a.ticks||[],u=[],p,o=b.labelWidth;b=b.labelHeight;if(a.direction=="x"){if(o==
null&&(o=Math.floor(E/(c.length>0?c.length:1))),b==null){u=[];for(e=0;e<c.length;++e)(p=c[e].label)&&u.push('<div class="tickLabel" style="float:left;width:'+o+'px">'+p+"</div>");u.length>0&&(u.push('<div style="clear:left"></div>'),c=d(u,"width:10000px;"),b=c.height(),c.remove())}}else if(o==null||b==null){for(e=0;e<c.length;++e)(p=c[e].label)&&u.push('<div class="tickLabel">'+p+"</div>");u.length>0&&(c=d(u,""),o==null&&(o=c.children().width()),b==null&&(b=c.find("div.tickLabel").height()),c.remove())}o==
null&&(o=0);b==null&&(b=0);a.labelWidth=o;a.labelHeight=b}function pa(a){var d=a.labelWidth,b=a.labelHeight,e=a.options.position,c=a.options.tickLength,u=f.grid.axisMargin,p=f.grid.labelMargin,o=a.direction=="x"?B:F,k=g.grep(o,function(a){return a&&a.options.position==e&&a.reserveSpace});g.inArray(a,k)==k.length-1&&(u=0);c==null&&(c="full");o=g.grep(o,function(a){return a&&a.reserveSpace});o=g.inArray(a,o)==0;!o&&c=="full"&&(c=5);isNaN(+c)||(p+=+c);a.direction=="x"?(b+=p,e=="bottom"?(n.bottom+=b+
u,a.box={top:G-n.bottom,height:b}):(a.box={top:n.top+u,height:b},n.top+=b+u)):(d+=p,e=="left"?(a.box={left:n.left+u,width:d},n.left+=d+u):(n.right+=d+u,a.box={left:E-n.right,width:d}));a.position=e;a.tickLength=c;a.box.padding=p;a.innermost=o}function ba(){var a,d=A();g.each(d,function(a,b){b.show=b.options.show;if(b.show==null)b.show=b.used;b.reserveSpace=b.show||b.options.reserveSpace;var e=b.options,d=+(e.min!=null?e.min:b.datamin),f=+(e.max!=null?e.max:b.datamax),l=f-d;if(l==0){if(l=f==0?1:0.01,
e.min==null&&(d-=l),e.max==null||e.min!=null)f+=l}else{var z=e.autoscaleMargin;z!=null&&(e.min==null&&(d-=l*z,d<0&&b.datamin!=null&&b.datamin>=0&&(d=0)),e.max==null&&(f+=l*z,f>0&&b.datamax!=null&&b.datamax<=0&&(f=0)))}b.min=d;b.max=f});allocatedAxes=g.grep(d,function(a){return a.reserveSpace});n.left=n.right=n.top=n.bottom=0;if(f.grid.show){g.each(allocatedAxes,function(a,b){qa(b);var e=b.options.ticks,d=[];e==null||typeof e=="number"&&e>0?d=b.tickGenerator(b):e&&(d=g.isFunction(e)?e({min:b.min,max:b.max}):
e);var f;b.ticks=[];for(e=0;e<d.length;++e){var l=null,z=d[e];typeof z=="object"?(f=+z[0],z.length>1&&(l=z[1])):f=+z;l==null&&(l=b.tickFormatter(f,b));isNaN(f)||b.ticks.push({v:f,label:l})}d=b.ticks;if(b.options.autoscaleMargin&&d.length>0){if(b.options.min==null)b.min=Math.min(b.min,d[0].v);if(b.options.max==null&&d.length>1)b.max=Math.max(b.max,d[d.length-1].v)}oa(b)});for(a=allocatedAxes.length-1;a>=0;--a)pa(allocatedAxes[a]);var b=f.grid.minBorderMargin;if(b==null)for(a=b=0;a<x.length;++a)b=Math.max(b,
x[a].points.radius+x[a].points.lineWidth/2);for(var e in n)n[e]+=f.grid.borderWidth,n[e]=Math.max(b,n[e])}O=E-n.left-n.right;K=G-n.bottom-n.top;g.each(d,function(a,b){na(b)});f.grid.show&&(g.each(allocatedAxes,function(a,b){b.direction=="x"?(b.box.left=n.left,b.box.width=O):(b.box.top=n.top,b.box.height=K)}),ra());sa()}function qa(a){var d=a.options,b=(a.max-a.min)/(typeof d.ticks=="number"&&d.ticks>0?d.ticks:0.3*Math.sqrt(a.direction=="x"?E:G)),e,c,f,p;if(d.mode=="time"){var o={second:1E3,minute:6E4,
hour:36E5,day:864E5,month:2592E6,year:525949.2*6E4};p=[[1,"second"],[2,"second"],[5,"second"],[10,"second"],[30,"second"],[1,"minute"],[2,"minute"],[5,"minute"],[10,"minute"],[30,"minute"],[1,"hour"],[2,"hour"],[4,"hour"],[8,"hour"],[12,"hour"],[1,"day"],[2,"day"],[3,"day"],[0.25,"month"],[0.5,"month"],[1,"month"],[2,"month"],[3,"month"],[6,"month"],[1,"year"]];e=0;d.minTickSize!=null&&(e=typeof d.tickSize=="number"?d.tickSize:d.minTickSize[0]*o[d.minTickSize[1]]);for(c=0;c<p.length-1;++c)if(b<(p[c][0]*
o[p[c][1]]+p[c+1][0]*o[p[c+1][1]])/2&&p[c][0]*o[p[c][1]]>=e)break;e=p[c][0];f=p[c][1];f=="year"&&(c=Math.pow(10,Math.floor(Math.log(b/o.year)/Math.LN10)),p=b/o.year/c,e=p<1.5?1:p<3?2:p<7.5?5:10,e*=c);a.tickSize=d.tickSize||[e,f];c=function(a){var b=[],e=a.tickSize[0],c=a.tickSize[1],d=new Date(a.min),f=e*o[c];c=="second"&&d.setUTCSeconds(w(d.getUTCSeconds(),e));c=="minute"&&d.setUTCMinutes(w(d.getUTCMinutes(),e));c=="hour"&&d.setUTCHours(w(d.getUTCHours(),e));c=="month"&&d.setUTCMonth(w(d.getUTCMonth(),
e));c=="year"&&d.setUTCFullYear(w(d.getUTCFullYear(),e));d.setUTCMilliseconds(0);f>=o.minute&&d.setUTCSeconds(0);f>=o.hour&&d.setUTCMinutes(0);f>=o.day&&d.setUTCHours(0);f>=o.day*4&&d.setUTCDate(1);f>=o.year&&d.setUTCMonth(0);var p=0,k=Number.NaN,l;do if(l=k,k=d.getTime(),b.push(k),c=="month")if(e<1){d.setUTCDate(1);var u=d.getTime();d.setUTCMonth(d.getUTCMonth()+1);var h=d.getTime();d.setTime(k+p*o.hour+(h-u)*e);p=d.getUTCHours();d.setUTCHours(0)}else d.setUTCMonth(d.getUTCMonth()+e);else c=="year"?
d.setUTCFullYear(d.getUTCFullYear()+e):d.setTime(k+f);while(k<a.max&&k!=l);return b};e=function(a,b){var e=new Date(a);if(d.timeformat!=null)return g.plot.formatDate(e,d.timeformat,d.monthNames);var c=b.tickSize[0]*o[b.tickSize[1]],f=b.max-b.min,k=d.twelveHourClock?" %p":"";fmt=c<o.minute?"%h:%M:%S"+k:c<o.day?f<2*o.day?"%h:%M"+k:"%b %d %h:%M"+k:c<o.month?"%b %d":c<o.year?f<o.year?"%b":"%b %y":"%y";return g.plot.formatDate(e,fmt,d.monthNames)}}else{f=d.tickDecimals;var k=-Math.floor(Math.log(b)/Math.LN10);
f!=null&&k>f&&(k=f);c=Math.pow(10,-k);p=b/c;if(p<1.5)e=1;else if(p<3){if(e=2,p>2.25&&(f==null||k+1<=f))e=2.5,++k}else e=p<7.5?5:10;e*=c;if(d.minTickSize!=null&&e<d.minTickSize)e=d.minTickSize;a.tickDecimals=Math.max(0,f!=null?f:k);a.tickSize=d.tickSize||e;c=function(a){var b=[],e=w(a.min,a.tickSize),c=0,d=Number.NaN,f;do f=d,d=e+c*a.tickSize,b.push(d),++c;while(d<a.max&&d!=f);return b};e=function(a,b){return a.toFixed(b.tickDecimals)}}if(d.alignTicksWithAxis!=null){var l=(a.direction=="x"?B:F)[d.alignTicksWithAxis-
1];if(l&&l.used&&l!=a){c=c(a);if(c.length>0){if(d.min==null)a.min=Math.min(a.min,c[0]);if(d.max==null&&c.length>1)a.max=Math.max(a.max,c[c.length-1])}c=function(a){var b=[],e,c;for(c=0;c<l.ticks.length;++c)e=(l.ticks[c].v-l.min)/(l.max-l.min),e=a.min+e*(a.max-a.min),b.push(e);return b};if(a.mode!="time"&&d.tickDecimals==null&&(b=Math.max(0,-Math.floor(Math.log(b)/Math.LN10)+1),p=c(a),!(p.length>1&&/\..*0$/.test((p[1]-p[0]).toFixed(b)))))a.tickDecimals=b}}a.tickGenerator=c;a.tickFormatter=g.isFunction(d.tickFormatter)?
function(a,b){return""+d.tickFormatter(a,b)}:e}function ca(){h.clearRect(0,0,E,G);var a=f.grid;if(a.show&&a.backgroundColor)h.save(),h.translate(n.left,n.top),h.fillStyle=da(f.grid.backgroundColor,K,0,"rgba(255, 255, 255, 0)"),h.fillRect(0,0,O,K),h.restore();a.show&&!a.aboveData&&ea();for(var d=0;d<x.length;++d){H(I.drawSeries,[h,x[d]]);var b=x[d];b.lines.show&&ta(b);b.bars.show&&ua(b);b.points.show&&va(b)}H(I.draw,[h]);a.show&&a.aboveData&&ea()}function fa(a,d){var b,e,c,f,p=A();for(i=0;i<p.length;++i)if(b=
p[i],b.direction==d&&(f=d+b.n+"axis",!a[f]&&b.n==1&&(f=d+"axis"),a[f])){e=a[f].from;c=a[f].to;break}a[f]||(b=d=="x"?B[0]:F[0],e=a[d+"1"],c=a[d+"2"]);e!=null&&c!=null&&e>c&&(f=e,e=c,c=f);return{from:e,to:c,axis:b}}function ea(){var a;h.save();h.translate(n.left,n.top);var d=f.grid.markings;if(d){if(g.isFunction(d)){var b=y.getAxes();b.xmin=b.xaxis.min;b.xmax=b.xaxis.max;b.ymin=b.yaxis.min;b.ymax=b.yaxis.max;d=d(b)}for(a=0;a<d.length;++a){b=d[a];var e=fa(b,"x"),c=fa(b,"y");if(e.from==null)e.from=e.axis.min;
if(e.to==null)e.to=e.axis.max;if(c.from==null)c.from=c.axis.min;if(c.to==null)c.to=c.axis.max;if(!(e.to<e.axis.min||e.from>e.axis.max||c.to<c.axis.min||c.from>c.axis.max))if(e.from=Math.max(e.from,e.axis.min),e.to=Math.min(e.to,e.axis.max),c.from=Math.max(c.from,c.axis.min),c.to=Math.min(c.to,c.axis.max),!(e.from==e.to&&c.from==c.to))e.from=e.axis.p2c(e.from),e.to=e.axis.p2c(e.to),c.from=c.axis.p2c(c.from),c.to=c.axis.p2c(c.to),e.from==e.to||c.from==c.to?(h.beginPath(),h.strokeStyle=b.color||f.grid.markingsColor,
h.lineWidth=b.lineWidth||f.grid.markingsLineWidth,h.moveTo(e.from,c.from),h.lineTo(e.to,c.to),h.stroke()):(h.fillStyle=b.color||f.grid.markingsColor,h.fillRect(e.from,c.to,e.to-e.from,c.from-c.to))}}b=A();d=f.grid.borderWidth;for(e=0;e<b.length;++e){c=b[e];a=c.box;var u=c.tickLength,p,o,k,l;if(c.show&&c.ticks.length!=0){h.strokeStyle=c.options.tickColor||g.color.parse(c.options.color).scale("a",0.22).toString();h.lineWidth=1;c.direction=="x"?(p=0,o=u=="full"?c.position=="top"?0:K:a.top-n.top+(c.position==
"top"?a.height:0)):(o=0,p=u=="full"?c.position=="left"?0:O:a.left-n.left+(c.position=="left"?a.width:0));c.innermost||(h.beginPath(),k=l=0,c.direction=="x"?k=O:l=K,h.lineWidth==1&&(p=Math.floor(p)+0.5,o=Math.floor(o)+0.5),h.moveTo(p,o),h.lineTo(p+k,o+l),h.stroke());h.beginPath();for(a=0;a<c.ticks.length;++a){var z=c.ticks[a].v;k=l=0;z<c.min||z>c.max||u=="full"&&d>0&&(z==c.min||z==c.max)||(c.direction=="x"?(p=c.p2c(z),l=u=="full"?-K:u,c.position=="top"&&(l=-l)):(o=c.p2c(z),k=u=="full"?-O:u,c.position==
"left"&&(k=-k)),h.lineWidth==1&&(c.direction=="x"?p=Math.floor(p)+0.5:o=Math.floor(o)+0.5),h.moveTo(p,o),h.lineTo(p+k,o+l))}h.stroke()}}if(d)h.lineWidth=d,h.strokeStyle=f.grid.borderColor,h.strokeRect(-d/2,-d/2,O+d,K+d);h.restore()}function ra(){j.find(".tickLabels").remove();for(var a=['<div class="tickLabels" style="font-size:smaller">'],d=A(),b=0;b<d.length;++b){var e=d[b],c=e.box;if(e.show){a.push('<div class="'+e.direction+"Axis "+e.direction+e.n+'Axis" style="color:'+e.options.color+'">');for(var f=
0;f<e.ticks.length;++f){var p=e.ticks[f];if(p.label&&!(p.v<e.min||p.v>e.max)){var o={},k;e.direction=="x"?(k="center",o.left=Math.round(n.left+e.p2c(p.v)-e.labelWidth/2),e.position=="bottom"?o.top=c.top+c.padding:o.bottom=G-(c.top+c.height-c.padding)):(o.top=Math.round(n.top+e.p2c(p.v)-e.labelHeight/2),e.position=="left"?(o.right=E-(c.left+c.width-c.padding),k="right"):(o.left=c.left+c.padding,k="left"));o.width=e.labelWidth;k=["position:absolute","text-align:"+k];for(var l in o)k.push(l+":"+o[l]+
"px");a.push('<div class="tickLabel" style="'+k.join(";")+'">'+p.label+"</div>")}}a.push("</div>")}}a.push("</div>");j.append(a.join(""))}function ta(a){function d(a,b,e,c,d){var f=a.points;a=a.pointsize;var j=null,u=null;h.beginPath();for(var g=a;g<f.length;g+=a){var s=f[g-a],m=f[g-a+1],r=f[g],v=f[g+1];if(!(s==null||r==null)){if(m<=v&&m<d.min){if(v<d.min)continue;s=(d.min-m)/(v-m)*(r-s)+s;m=d.min}else if(v<=m&&v<d.min){if(m<d.min)continue;r=(d.min-m)/(v-m)*(r-s)+s;v=d.min}if(m>=v&&m>d.max){if(v>
d.max)continue;s=(d.max-m)/(v-m)*(r-s)+s;m=d.max}else if(v>=m&&v>d.max){if(m>d.max)continue;r=(d.max-m)/(v-m)*(r-s)+s;v=d.max}if(s<=r&&s<c.min){if(r<c.min)continue;m=(c.min-s)/(r-s)*(v-m)+m;s=c.min}else if(r<=s&&r<c.min){if(s<c.min)continue;v=(c.min-s)/(r-s)*(v-m)+m;r=c.min}if(s>=r&&s>c.max){if(r>c.max)continue;m=(c.max-s)/(r-s)*(v-m)+m;s=c.max}else if(r>=s&&r>c.max){if(s>c.max)continue;v=(c.max-s)/(r-s)*(v-m)+m;r=c.max}(s!=j||m!=u)&&h.moveTo(c.p2c(s)+b,d.p2c(m)+e);j=r;u=v;h.lineTo(c.p2c(r)+b,d.p2c(v)+
e)}}h.stroke()}function b(a,b,c){var d=a.points;a=a.pointsize;for(var e=Math.min(Math.max(0,c.min),c.max),f=0,j=!1,u=1,g=0,s=0;;){if(a>0&&f>d.length+a)break;f+=a;var m=d[f-a],r=d[f-a+u],v=d[f],n=d[f+u];if(j){if(a>0&&m!=null&&v==null){s=f;a=-a;u=2;continue}if(a<0&&f==g+a){h.fill();j=!1;a=-a;u=1;f=g=s+a;continue}}if(!(m==null||v==null)){if(m<=v&&m<b.min){if(v<b.min)continue;r=(b.min-m)/(v-m)*(n-r)+r;m=b.min}else if(v<=m&&v<b.min){if(m<b.min)continue;n=(b.min-m)/(v-m)*(n-r)+r;v=b.min}if(m>=v&&m>b.max){if(v>
b.max)continue;r=(b.max-m)/(v-m)*(n-r)+r;m=b.max}else if(v>=m&&v>b.max){if(m>b.max)continue;n=(b.max-m)/(v-m)*(n-r)+r;v=b.max}j||(h.beginPath(),h.moveTo(b.p2c(m),c.p2c(e)),j=!0);if(r>=c.max&&n>=c.max)h.lineTo(b.p2c(m),c.p2c(c.max)),h.lineTo(b.p2c(v),c.p2c(c.max));else if(r<=c.min&&n<=c.min)h.lineTo(b.p2c(m),c.p2c(c.min)),h.lineTo(b.p2c(v),c.p2c(c.min));else{var q=m,t=v;if(r<=n&&r<c.min&&n>=c.min)m=(c.min-r)/(n-r)*(v-m)+m,r=c.min;else if(n<=r&&n<c.min&&r>=c.min)v=(c.min-r)/(n-r)*(v-m)+m,n=c.min;if(r>=
n&&r>c.max&&n<=c.max)m=(c.max-r)/(n-r)*(v-m)+m,r=c.max;else if(n>=r&&n>c.max&&r<=c.max)v=(c.max-r)/(n-r)*(v-m)+m,n=c.max;m!=q&&h.lineTo(b.p2c(q),c.p2c(r));h.lineTo(b.p2c(m),c.p2c(r));h.lineTo(b.p2c(v),c.p2c(n));v!=t&&(h.lineTo(b.p2c(v),c.p2c(n)),h.lineTo(b.p2c(t),c.p2c(n)))}}}}h.save();h.translate(n.left,n.top);h.lineJoin="round";var e=a.lines.lineWidth,c=a.shadowSize;if(e>0&&c>0){h.lineWidth=c;h.strokeStyle="rgba(0,0,0,0.1)";var f=Math.PI/18;d(a.datapoints,Math.sin(f)*(e/2+c/2),Math.cos(f)*(e/2+
c/2),a.xaxis,a.yaxis);h.lineWidth=c/2;d(a.datapoints,Math.sin(f)*(e/2+c/4),Math.cos(f)*(e/2+c/4),a.xaxis,a.yaxis)}h.lineWidth=e;h.strokeStyle=a.color;if(c=X(a.lines,a.color,0,K))h.fillStyle=c,b(a.datapoints,a.xaxis,a.yaxis);e>0&&d(a.datapoints,0,0,a.xaxis,a.yaxis);h.restore()}function va(a){function d(a,b,c,d,e,f,j,u){var g=a.points;a=a.pointsize;for(var n=0;n<g.length;n+=a){var m=g[n],r=g[n+1];if(!(m==null||m<f.min||m>f.max||r<j.min||r>j.max)){h.beginPath();m=f.p2c(m);r=j.p2c(r)+d;u=="circle"?h.arc(m,
r,b,0,e?Math.PI:Math.PI*2,!1):u(h,m,r,b,e);h.closePath();if(c)h.fillStyle=c,h.fill();h.stroke()}}}h.save();h.translate(n.left,n.top);var b=a.points.lineWidth,e=a.shadowSize,c=a.points.radius,f=a.points.symbol;if(b>0&&e>0)e/=2,h.lineWidth=e,h.strokeStyle="rgba(0,0,0,0.1)",d(a.datapoints,c,null,e+e/2,!0,a.xaxis,a.yaxis,f),h.strokeStyle="rgba(0,0,0,0.2)",d(a.datapoints,c,null,e/2,!0,a.xaxis,a.yaxis,f);h.lineWidth=b;h.strokeStyle=a.color;d(a.datapoints,c,X(a.points,a.color),0,!1,a.xaxis,a.yaxis,f);h.restore()}
function ga(a,d,b,e,c,f,j,h,k,l,g,n){var q,t,x,s;g?(s=t=x=!0,q=!1,g=b,b=d+e,c=d+c,a<g&&(d=a,a=g,g=d,q=!0,t=!1)):(q=t=x=!0,s=!1,g=a+e,a+=c,c=b,b=d,b<c&&(d=b,b=c,c=d,s=!0,x=!1));if(!(a<h.min||g>h.max||b<k.min||c>k.max)){if(g<h.min)g=h.min,q=!1;if(a>h.max)a=h.max,t=!1;if(c<k.min)c=k.min,s=!1;if(b>k.max)b=k.max,x=!1;g=h.p2c(g);c=k.p2c(c);a=h.p2c(a);b=k.p2c(b);if(j)l.beginPath(),l.moveTo(g,c),l.lineTo(g,b),l.lineTo(a,b),l.lineTo(a,c),l.fillStyle=j(c,b),l.fill();if(n>0&&(q||t||x||s))l.beginPath(),l.moveTo(g,
c+f),q?l.lineTo(g,b+f):l.moveTo(g,b+f),x?l.lineTo(a,b+f):l.moveTo(a,b+f),t?l.lineTo(a,c+f):l.moveTo(a,c+f),s?l.lineTo(g,c+f):l.moveTo(g,c+f),l.stroke()}}function ua(a){h.save();h.translate(n.left,n.top);h.lineWidth=a.bars.lineWidth;h.strokeStyle=a.color;var d=a.bars.align=="left"?0:-a.bars.barWidth/2;(function(b,d,c,f,g,j,k){var l=b.points;b=b.pointsize;for(var n=0;n<l.length;n+=b)l[n]!=null&&ga(l[n],l[n+1],l[n+2],d,c,f,g,j,k,h,a.bars.horizontal,a.bars.lineWidth)})(a.datapoints,d,d+a.bars.barWidth,
0,a.bars.fill?function(b,d){return X(a.bars,a.color,b,d)}:null,a.xaxis,a.yaxis);h.restore()}function X(a,d,b,e){var c=a.fill;if(!c)return null;if(a.fillColor)return da(a.fillColor,b,e,d);a=g.color.parse(d);a.a=typeof c=="number"?c:0.4;a.normalize();return a.toString()}function sa(){j.find(".legend").remove();if(f.legend.show){for(var a=[],d=!1,b=f.legend.labelFormatter,e,c,h=0;h<x.length;++h)if(e=x[h],c=e.label)h%f.legend.noColumns==0&&(d&&a.push("</tr>"),a.push("<tr>"),d=!0),b&&(c=b(c,e)),a.push('<td class="legendColorBox"><div style="border:1px solid '+
f.legend.labelBoxBorderColor+';padding:1px"><div style="width:4px;height:0;border:5px solid '+e.color+';overflow:hidden"></div></div></td><td class="legendLabel">'+c+"</td>");d&&a.push("</tr>");if(a.length!=0)if(d='<table style="font-size:smaller;color:'+f.grid.color+'">'+a.join("")+"</table>",f.legend.container!=null)g(f.legend.container).html(d);else if(a="",b=f.legend.position,e=f.legend.margin,e[0]==null&&(e=[e,e]),b.charAt(0)=="n"?a+="top:"+(e[1]+n.top)+"px;":b.charAt(0)=="s"&&(a+="bottom:"+
(e[1]+n.bottom)+"px;"),b.charAt(1)=="e"?a+="right:"+(e[0]+n.right)+"px;":b.charAt(1)=="w"&&(a+="left:"+(e[0]+n.left)+"px;"),d=g('<div class="legend">'+d.replace('style="','style="position:absolute;'+a+";")+"</div>").appendTo(j),f.legend.backgroundOpacity!=0){b=f.legend.backgroundColor;if(b==null)b=(b=f.grid.backgroundColor)&&typeof b=="string"?g.color.parse(b):g.color.extract(d,"background-color"),b.a=1,b=b.toString();e=d.children();g('<div style="position:absolute;width:'+e.width()+"px;height:"+
e.height()+"px;"+a+"background-color:"+b+';"> </div>').prependTo(d).css("opacity",f.legend.backgroundOpacity)}}}function ha(a){f.grid.hoverable&&Y("plothover",a,function(a){return a.hoverable!=!1})}function ia(a){f.grid.hoverable&&Y("plothover",a,function(){return!1})}function ja(a){Y("plotclick",a,function(a){return a.clickable!=!1})}function Y(a,d,b){var e=J.offset(),c=d.pageX-e.left-n.left,h=d.pageY-e.top-n.top,g=T({left:c,top:h});g.pageX=d.pageX;g.pageY=d.pageY;d=f.grid.mouseActiveRadius;var o=
d*d+1,k=null,l,q;for(l=x.length-1;l>=0;--l)if(b(x[l])){var t=x[l],y=t.xaxis,w=t.yaxis,C=t.datapoints.points,s=t.datapoints.pointsize,m=y.c2p(c),r=w.c2p(h),v=d/y.scale,D=d/w.scale;if(y.options.inverseTransform)v=Number.MAX_VALUE;if(w.options.inverseTransform)D=Number.MAX_VALUE;if(t.lines.show||t.points.show)for(q=0;q<C.length;q+=s){var B=C[q],A=C[q+1];if(B!=null&&!(B-m>v||B-m<-v||A-r>D||A-r<-D))B=Math.abs(y.p2c(B)-c),A=Math.abs(w.p2c(A)-h),A=B*B+A*A,A<o&&(o=A,k=[l,q/s])}if(t.bars.show&&!k){y=t.bars.align==
"left"?0:-t.bars.barWidth/2;t=y+t.bars.barWidth;for(q=0;q<C.length;q+=s)if(B=C[q],A=C[q+1],w=C[q+2],B!=null&&(x[l].bars.horizontal?m<=Math.max(w,B)&&m>=Math.min(w,B)&&r>=A+y&&r<=A+t:m>=B+y&&m<=B+t&&r>=Math.min(w,A)&&r<=Math.max(w,A)))k=[l,q/s]}}k?(l=k[0],q=k[1],s=x[l].datapoints.pointsize,b={datapoint:x[l].datapoints.points.slice(q*s,(q+1)*s),dataIndex:q,series:x[l],seriesIndex:l}):b=null;if(b)b.pageX=parseInt(b.series.xaxis.p2c(b.datapoint[0])+e.left+n.left),b.pageY=parseInt(b.series.yaxis.p2c(b.datapoint[1])+
e.top+n.top);if(f.grid.autoHighlight){for(e=0;e<M.length;++e)c=M[e],c.auto==a&&(!b||!(c.series==b.series&&c.point[0]==b.datapoint[0]&&c.point[1]==b.datapoint[1]))&&ka(c.series,c.point);b&&la(b.series,b.datapoint,a)}j.trigger(a,[g,b])}function W(){U||(U=setTimeout(wa,30))}function wa(){U=null;D.save();D.clearRect(0,0,E,G);D.translate(n.left,n.top);var a,d;for(a=0;a<M.length;++a)if(d=M[a],d.series.bars.show)xa(d.series,d.point);else{var b=d.series,e=d.point;d=e[0];e=e[1];var c=b.xaxis,f=b.yaxis;if(!(d<
c.min||d>c.max||e<f.min||e>f.max)){var h=b.points.radius+b.points.lineWidth/2;D.lineWidth=h;D.strokeStyle=g.color.parse(b.color).scale("a",0.5).toString();h*=1.5;d=c.p2c(d);e=f.p2c(e);D.beginPath();b.points.symbol=="circle"?D.arc(d,e,h,0,2*Math.PI,!1):b.points.symbol(D,d,e,h,!1);D.closePath();D.stroke()}}D.restore();H(I.drawOverlay,[D])}function la(a,d,b){typeof a=="number"&&(a=x[a]);if(typeof d=="number"){var e=a.datapoints.pointsize;d=a.datapoints.points.slice(e*d,e*(d+1))}e=ma(a,d);if(e==-1)M.push({series:a,
point:d,auto:b}),W();else if(!b)M[e].auto=!1}function ka(a,d){a==null&&d==null&&(M=[],W());typeof a=="number"&&(a=x[a]);typeof d=="number"&&(d=a.data[d]);var b=ma(a,d);b!=-1&&(M.splice(b,1),W())}function ma(a,d){for(var b=0;b<M.length;++b){var e=M[b];if(e.series==a&&e.point[0]==d[0]&&e.point[1]==d[1])return b}return-1}function xa(a,d){D.lineWidth=a.bars.lineWidth;D.strokeStyle=g.color.parse(a.color).scale("a",0.5).toString();var b=g.color.parse(a.color).scale("a",0.5).toString(),e=a.bars.align=="left"?
0:-a.bars.barWidth/2;ga(d[0],d[1],d[2]||0,e,e+a.bars.barWidth,0,function(){return b},a.xaxis,a.yaxis,D,a.bars.horizontal,a.bars.lineWidth)}function da(a,d,b,e){if(typeof a=="string")return a;else{d=h.createLinearGradient(0,b,0,d);b=0;for(var c=a.colors.length;b<c;++b){var f=a.colors[b];if(typeof f!="string"){var j=g.color.parse(e);f.brightness!=null&&(j=j.scale("rgb",f.brightness));f.opacity!=null&&(j.a*=f.opacity);f=j.toString()}d.addColorStop(b/(c-1),f)}return d}}var x=[],f={colors:["#edc240","#afd8f8",
"#cb4b4b","#4da74d","#9440ed"],legend:{show:!0,noColumns:1,labelFormatter:null,labelBoxBorderColor:"#ccc",container:null,position:"ne",margin:5,backgroundColor:null,backgroundOpacity:0.85},xaxis:{show:null,position:"bottom",mode:null,color:null,tickColor:null,transform:null,inverseTransform:null,min:null,max:null,autoscaleMargin:null,ticks:null,tickFormatter:null,labelWidth:null,labelHeight:null,reserveSpace:null,tickLength:null,alignTicksWithAxis:null,tickDecimals:null,tickSize:null,minTickSize:null,
monthNames:null,timeformat:null,twelveHourClock:!1},yaxis:{autoscaleMargin:0.02,position:"left"},xaxes:[],yaxes:[],series:{points:{show:!1,radius:3,lineWidth:2,fill:!0,fillColor:"#ffffff",symbol:"circle"},lines:{lineWidth:2,fill:!1,fillColor:null,steps:!1},bars:{show:!1,lineWidth:2,barWidth:1,fill:!0,fillColor:null,align:"left",horizontal:!1},shadowSize:3},grid:{show:!0,aboveData:!1,color:"#545454",backgroundColor:null,borderColor:null,tickColor:null,labelMargin:5,axisMargin:8,borderWidth:2,minBorderMargin:null,
markings:null,markingsColor:"#f4f4f4",markingsLineWidth:2,clickable:!1,hoverable:!1,autoHighlight:!0,mouseActiveRadius:10},hooks:{}},R=null,S=null,J=null,h=null,D=null,B=[],F=[],n={left:0,right:0,top:0,bottom:0},E=0,G=0,O=0,K=0,I={processOptions:[],processRawData:[],processDatapoints:[],drawSeries:[],draw:[],bindEvents:[],drawOverlay:[],shutdown:[]},y=this;y.setData=Z;y.setupGrid=ba;y.draw=ca;y.getPlaceholder=function(){return j};y.getCanvas=function(){return R};y.getPlotOffset=function(){return n};
y.width=function(){return O};y.height=function(){return K};y.offset=function(){var a=J.offset();a.left+=n.left;a.top+=n.top;return a};y.getData=function(){return x};y.getAxes=function(){var a={};g.each(B.concat(F),function(d,b){b&&(a[b.direction+(b.n!=1?b.n:"")+"axis"]=b)});return a};y.getXAxes=function(){return B};y.getYAxes=function(){return F};y.c2p=T;y.p2c=function(a){var d={},b,e,c;for(b=0;b<B.length;++b)if((e=B[b])&&e.used)if(c="x"+e.n,a[c]==null&&e.n==1&&(c="x"),a[c]!=null){d.left=e.p2c(a[c]);
break}for(b=0;b<F.length;++b)if((e=F[b])&&e.used)if(c="y"+e.n,a[c]==null&&e.n==1&&(c="y"),a[c]!=null){d.top=e.p2c(a[c]);break}return d};y.getOptions=function(){return f};y.highlight=la;y.unhighlight=ka;y.triggerRedrawOverlay=W;y.pointOffset=function(a){return{left:parseInt(B[N(a,"x")-1].p2c(+a.x)+n.left),top:parseInt(F[N(a,"y")-1].p2c(+a.y)+n.top)}};y.shutdown=function(){U&&clearTimeout(U);J.unbind("mousemove",ha);J.unbind("mouseleave",ia);J.unbind("click",ja);H(I.shutdown,[J])};y.resize=function(){L();
aa(R);aa(S)};y.hooks=I;(function(){for(var a=0;a<q.length;++a){var d=q[a];d.init(y);d.options&&g.extend(!0,f,d.options)}})(y);(function(a){g.extend(!0,f,a);if(f.xaxis.color==null)f.xaxis.color=f.grid.color;if(f.yaxis.color==null)f.yaxis.color=f.grid.color;if(f.xaxis.tickColor==null)f.xaxis.tickColor=f.grid.tickColor;if(f.yaxis.tickColor==null)f.yaxis.tickColor=f.grid.tickColor;if(f.grid.borderColor==null)f.grid.borderColor=f.grid.color;if(f.grid.tickColor==null)f.grid.tickColor=g.color.parse(f.grid.color).scale("a",
0.22).toString();for(a=0;a<Math.max(1,f.xaxes.length);++a)f.xaxes[a]=g.extend(!0,{},f.xaxis,f.xaxes[a]);for(a=0;a<Math.max(1,f.yaxes.length);++a)f.yaxes[a]=g.extend(!0,{},f.yaxis,f.yaxes[a]);if(f.xaxis.noTicks&&f.xaxis.ticks==null)f.xaxis.ticks=f.xaxis.noTicks;if(f.yaxis.noTicks&&f.yaxis.ticks==null)f.yaxis.ticks=f.yaxis.noTicks;if(f.x2axis)f.xaxes[1]=g.extend(!0,{},f.xaxis,f.x2axis),f.xaxes[1].position="top";if(f.y2axis)f.yaxes[1]=g.extend(!0,{},f.yaxis,f.y2axis),f.yaxes[1].position="right";if(f.grid.coloredAreas)f.grid.markings=
f.grid.coloredAreas;if(f.grid.coloredAreasColor)f.grid.markingsColor=f.grid.coloredAreasColor;f.lines&&g.extend(!0,f.series.lines,f.lines);f.points&&g.extend(!0,f.series.points,f.points);f.bars&&g.extend(!0,f.series.bars,f.bars);if(f.shadowSize!=null)f.series.shadowSize=f.shadowSize;for(a=0;a<f.xaxes.length;++a)P(B,a+1).options=f.xaxes[a];for(a=0;a<f.yaxes.length;++a)P(F,a+1).options=f.yaxes[a];for(var d in I)f.hooks[d]&&f.hooks[d].length&&(I[d]=I[d].concat(f.hooks[d]));H(I.processOptions,[f])})(V);
(function(){var a;a=j.children("canvas.base");var d=j.children("canvas.overlay");a.length==0||d==0?(j.html(""),j.css({padding:0}),j.css("position")=="static"&&j.css("position","relative"),L(),R=$(!0,"base"),S=$(!1,"overlay"),a=!1):(R=a.get(0),S=d.get(0),a=!0);h=R.getContext("2d");D=S.getContext("2d");J=g([S,R]);a&&(j.data("plot").shutdown(),y.resize(),D.clearRect(0,0,E,G),J.unbind(),j.children().not([R,S]).remove());j.data("plot",y)})();Z(t);ba();ca();f.grid.hoverable&&(J.mousemove(ha),J.mouseleave(ia));
f.grid.clickable&&J.click(ja);H(I.bindEvents,[J]);var M=[],U=null}function w(g,t){return t*Math.floor(g/t)}g.plot=function(j,t,w){return new L(g(j),t,w,g.plot.plugins)};g.plot.version="0.7";g.plot.plugins=[];g.plot.formatDate=function(g,t,w){var q=function(g){g=""+g;return g.length==1?"0"+g:g},H=[],L=!1,N=!1,A=g.getUTCHours(),T=A<12;w==null&&(w=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]);t.search(/%p|%P/)!=-1&&(A>12?A-=12:A==0&&(A=12));for(var P=0;P<t.length;++P){var C=
t.charAt(P);if(L){switch(C){case "h":C=""+A;break;case "H":C=q(A);break;case "M":C=q(g.getUTCMinutes());break;case "S":C=q(g.getUTCSeconds());break;case "d":C=""+g.getUTCDate();break;case "m":C=""+(g.getUTCMonth()+1);break;case "y":C=""+g.getUTCFullYear();break;case "b":C=""+w[g.getUTCMonth()];break;case "p":C=T?"am":"pm";break;case "P":C=T?"AM":"PM";break;case "0":C="",N=!0}C&&N&&(C=q(C),N=!1);H.push(C);N||(L=!1)}else C=="%"?L=!0:H.push(C)}return H.join("")}})(jQuery);